# PEP 8 Speaks configuration according to
# https://github.com/OrkoHunter/pep8speaks

scanner:
  diff_only: False  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.
  linter: flake8  # Other option is pycodestyle

flake8:  # Same as scanner.linter value. Other option is pycodestyle
  # Compatible black configuration according to
  # https://github.com/psf/black/blob/master/docs/compatible_configs.md#flake8
  max-line-length: 88  # Default is 79 in PEP 8
  ignore:  # Errors and warnings to ignore
    - E203  # Whitespace before ':'
    - W503  # Line break before binary operator

no_blank_comment: False  # If False, a comment is made on PR without any errors.
descending_issues_order: True  # If True, PEP 8 issues in message will be displayed in descending order of line numbers in the file
only_mention_files_with_errors: True  # If False, a separate status section for each file is made in the comment.

message:  # Customize the comment made by the bot
  opened:  # Messages when a new PR is submitted
    header: "Hello @{name}! Thanks for opening this PR. "
            # The keyword {name} is converted into the author's username
    footer: "Do see the [Black](https://github.com/psf/black) code style. "
  updated:  # Messages when new commits are added to the PR
    header: "Hello @{name}! Thanks for updating this PR. "
    footer: ""  # Why to comment the link to the style guide everytime? :)
  no_errors: "There are currently no `Black` (PEP 8) issues detected in this Pull Request. Cheers! :beers: "
