channels:
  - defaults  # prefer installing packages from conda-main over conda-forge, will install Intel MKL for numpy)
  - conda-forge  # preferring conda-forge would install OpenBLAS for numpy
dependencies:
  - jinja2
  - natsort
  - pandas
