name: ReTiSAR
channels:
  - defaults  # prefer installing packages from conda-main over conda-forge, will install Intel MKL for numpy)
  - conda-forge  # preferring conda-forge would install OpenBLAS for numpy
dependencies:
  - cffi  # for jack-client/samplerate/pysoundfile from conda
  - matplotlib
  - netCDF4  # for pysofaconventions from conda
  - numpy >= 1.15.4
  - pip
#  - psutil  # for adjusting process priority, currently not used
  - pycparser  # for jack-client/samplerate/pysoundfile from conda
  - pyfftw
  - pyserial >= 3.4
  - pysoundfile >= 0.10.2  # on Windows you need to install soundfile via pip
  - python >= 3.7
  - scipy
  - pip:
    - jack-client >= 0.4.4
    - python-osc
    - pysofaconventions >= 0.1.5
    - samplerate
    - sound-field-analysis >= 2020.1.30
    - -e .
